import ContainerSectionHero from "../components/ContainerSectionHero";
import ContainerSectionTestimonials from "../components/ContainerSectionTestimonials";
import ContainerSectionContextSelecti from "../components/ContainerSectionContextSelecti";
import ContainerFeaturesOverall from "../components/ContainerFeaturesOverall";
import ContainerFeatureLeft from "../components/ContainerFeatureLeft";
import ContainerFeatureRight from "../components/ContainerFeatureRight";
import ContainerSectionPricing from "../components/ContainerSectionPricing";
import ContainerButtonStores from "../components/ContainerButtonStores";
import Footer from "../components/Footer";

const Containermain = () => {
  return (
    <div className="relative w-full overflow-hidden flex flex-col items-center justify-start">
      <ContainerSectionHero
        containerHeroLogoUrl="/imagelogo@2x.png"
        containerHeroAppStoreUrl="/imageappstore@2x.png"
        containerHeroGooglePlayUrl="/imagegoogleplay@2x.png"
        containersectionheroWidth="120rem"
        containersectionheroHeight="67.5rem"
        containersectionheroPadding="0rem 12.5rem"
        containerdivGap="8rem"
        containerdivMaxWidth="95rem"
        containernav2Padding="1.5rem 0rem 0rem"
        containerdivWidth="10.31rem"
        containerdivHeight="2rem"
        imagelogoIconTop="0rem"
        imagelogoIconLeft="0rem"
        imagelogoIconWidth="7rem"
        imagelogoIconHeight="2rem"
        imagelogoIconObjectFit="cover"
        containerdivlinksMaxWidth="50rem"
        textlabelFontSize="1.25rem"
        textlabelLineHeight="2.25rem"
        textlabelFontSize1="1.25rem"
        textlabelLineHeight1="2.25rem"
        textlabelFontSize2="1.25rem"
        textlabelLineHeight2="2.25rem"
        textlabelFontSize3="1.25rem"
        textlabelLineHeight3="2.25rem"
        textlabelFontSize4="1.25rem"
        textlabelLineHeight4="2.25rem"
        buttonmenuWidth="4rem"
        buttonmenuHeight="4rem"
        buttonmenuPadding="1rem"
        buttonmenuGap="1rem"
        iconline3horizontalWidth="1.5rem"
        iconline3horizontalHeight="1.5rem"
        textstrongFontSize="1rem"
        textstrongLineHeight="2rem"
        iconarrowrightWidth="1.5rem"
        iconarrowrightHeight="1.5rem"
        buttonctaPadding="1rem 2rem"
        buttonctaGap="1rem"
        iconarrowleftWidth="1.5rem"
        iconarrowleftHeight="1.5rem"
        textstrongFontSize1="1rem"
        textstrongLineHeight1="2rem"
        iconarrowrightWidth1="1.5rem"
        iconarrowrightHeight1="1.5rem"
        containerdivGap1="8rem"
        containerarticleGap="3rem"
        containerarticleMaxWidth="43.75rem"
        containerdivheaderGap="1.5rem"
        texth1FontSize="6rem"
        texth1LineHeight="6rem"
        texth1FontSize1="6rem"
        texth1LineHeight1="6rem"
        texth1FontSize2="6rem"
        texth1LineHeight2="6rem"
        textpFontSize="1.25rem"
        textpLineHeight="2.25rem"
        containerdivstorebuttonsGap="2rem"
        imageappstoreIconWidth="12.98rem"
        imageappstoreIconHeight="3.75rem"
        imageappstoreIconObjectFit="cover"
        imagegoogleplayIconWidth="12.96rem"
        imagegoogleplayIconHeight="3.75rem"
        imagegoogleplayIconObjectFit="cover"
        containerdivratingGap="1rem"
        containerdivtextGap="0.5rem"
        textlabelFontSize5="1.5rem"
        textlabelLineHeight5="2.5rem"
        textlabelCursor="pointer"
        textspanFontSize="1.5rem"
        textspanLineHeight="2.5rem"
        imageiconstarWidth="2rem"
        imageiconstarHeight="2rem"
        imageiconstarWidth1="2rem"
        imageiconstarHeight1="2rem"
        imageiconstarWidth2="2rem"
        imageiconstarHeight2="2rem"
        imageiconstarWidth3="2rem"
        imageiconstarHeight3="2rem"
        imageiconstarWidth4="2rem"
        imageiconstarHeight4="2rem"
        imageheroIconMaxWidth="43.75rem"
        imageheroIconHeight="66.63rem"
      />
      <ContainerSectionTestimonials
        containerTestimonialsImageLogoUrl="/imagelogoifab1.svg"
        containerTestimonialsImageMockupUrl="/imagemockup2@2x.png"
        containersectiontestimoniWidth="120rem"
        containersectiontestimoniPadding="16rem 12.5rem 8rem"
        containerdivfootballRulesWidth="95rem"
        containerdivfootballRulesPadding="4rem"
        containerdivcontentGap="4rem"
        containerdivcontentMaxWidth="50rem"
        textspanFontSize="2rem"
        textspanLineHeight="2rem"
        textspanWidth="23rem"
        textstrongFontSize="4rem"
        textstrongLineHeight="3.5rem"
        textstrongWidth="23rem"
        containerdivtextGap="1rem"
        texth6FontSize="1.5rem"
        texth6LineHeight="2.5rem"
        texth6Margin="0"
        texth6FontWeight="700"
        textblockquoteFontSize="1.25rem"
        textblockquoteLineHeight="2.25rem"
        textblockquoteMargin="0"
        containerdivpersonDetailsGap="1rem"
        imagepersonIconWidth="5rem"
        imagepersonIconHeight="5rem"
        textlabelFontSize="1.25rem"
        textlabelLineHeight="2.25rem"
        textsFontSize="1rem"
        textsLineHeight="2rem"
        imagelogoifabIconWidth="10.94rem"
        imagelogoifabIconHeight="4.5rem"
        imagelogoifabIconObjectFit="cover"
        imagemockup2IconRight="1.56rem"
        imagemockup2IconWidth="21.88rem"
        imagemockup2IconHeight="35rem"
        imagemockup1IconRight="12.5rem"
        imagemockup1IconWidth="25rem"
        imagemockup1IconHeight="40rem"
      />
      <ContainerSectionContextSelecti />
      <ContainerFeaturesOverall />
      <ContainerFeatureLeft
        featureHeaderLight="Official"
        featureHeaderBold="Partners"
        featureParagraphText="Elevate your organization's presence and create mutually beneficial partnerships with the Official Partners feature. ROSA provides dedicated spaces for sponsors and partners to showcase their brand through images, banners, and videos, allowing you to monetize your app and deliver value to your supporters. Attract potential sponsors and enhance your app's visual appeal with this powerful feature."
        featureMockupImageUrl="/imagemockup@2x.png"
        containersectionfeature1Width="120rem"
        containersectionfeature1Padding="16rem 12.5rem 12.5rem"
        containersectionfeature1Gap="8rem"
        containerarticlefeatureHeight="33rem"
        containerarticlefeatureGap="2rem"
        textsectionTitleh1Gap="1.5rem"
        texth1lightFontSize="6rem"
        texth1lightLineHeight="6rem"
        texth1lightMargin="0"
        texth1boldFontSize="6rem"
        texth1boldLineHeight="6rem"
        texth1boldMargin="0"
        textpFontSize="1.5rem"
        textpLineHeight="2.5rem"
        textpMargin="0"
        imagemockupIconWidth="43.5rem"
        imagemockupIconHeight="73.81rem"
        showSecondaryText
        showPrimaryText
      />
      <ContainerFeatureRight
        featureMockupImage="/imagemockup3@2x.png"
        featureHeaderLight="Documents"
        featureHeaderBold="Selection"
        containersectionfeature2Width="120rem"
        containersectionfeature2Padding="16rem 12.5rem 12.5rem"
        containersectionfeature2Gap="8rem"
        imagemockupIconWidth="43.5rem"
        imagemockupIconHeight="73.81rem"
        containerarticlefeatureHeight="33rem"
        containerarticlefeatureGap="2rem"
        textsectionTitleh1Gap="1.5rem"
        texth1lightFontSize="6rem"
        texth1lightLineHeight="6rem"
        texth1lightMargin="0"
        texth1boldFontSize="6rem"
        texth1boldLineHeight="6rem"
        texth1boldMargin="0"
        textpFontSize="1.5rem"
        textpLineHeight="2.5rem"
        textpMargin="0"
        showSecondaryText
        showPrimaryText
      />
      <ContainerFeatureLeft
        featureHeaderLight="Manage"
        featureHeaderBold="Competitions"
        featureParagraphText="Effortlessly orchestrate diverse competitions within your sporting organization using the Manage Competitions feature. ROSA offers a versatile platform that allows you to create and customize competitions with distinct rules, ensuring precision and alignment with the specific needs of each event. Whether it's men's and women's competitions or various sporting disciplines, ROSA empowers you to manage them all seamlessly, enhancing the efficiency and accuracy of your organization's operations."
        featureMockupImageUrl="/imagemockup4@2x.png"
        containersectionfeature1Width="120rem"
        containersectionfeature1Padding="16rem 12.5rem 12.5rem"
        containersectionfeature1Gap="8rem"
        containerarticlefeatureHeight="33rem"
        containerarticlefeatureGap="2rem"
        textsectionTitleh1Gap="1.5rem"
        texth1lightFontSize="6rem"
        texth1lightLineHeight="6rem"
        texth1lightMargin="0"
        texth1boldFontSize="6rem"
        texth1boldLineHeight="6rem"
        texth1boldMargin="0"
        textpFontSize="1.5rem"
        textpLineHeight="2.5rem"
        textpMargin="0"
        imagemockupIconWidth="43.5rem"
        imagemockupIconHeight="73.81rem"
        showSecondaryText
        showPrimaryText
      />
      <ContainerFeatureRight
        featureMockupImage="/imagemockup5@2x.png"
        featureHeaderLight="Featured"
        featureHeaderBold="Resources"
        containersectionfeature2Width="120rem"
        containersectionfeature2Padding="16rem 12.5rem 12.5rem"
        containersectionfeature2Gap="8rem"
        imagemockupIconWidth="43.5rem"
        imagemockupIconHeight="73.81rem"
        containerarticlefeatureHeight="33rem"
        containerarticlefeatureGap="2rem"
        textsectionTitleh1Gap="1.5rem"
        texth1lightFontSize="6rem"
        texth1lightLineHeight="6rem"
        texth1lightMargin="0"
        texth1boldFontSize="6rem"
        texth1boldLineHeight="6rem"
        texth1boldMargin="0"
        textpFontSize="1.5rem"
        textpLineHeight="2.5rem"
        textpMargin="0"
        showSecondaryText
        showPrimaryText
      />
      <ContainerSectionPricing />
      <ContainerButtonStores />
      <Footer />
    </div>
  );
};

export default Containermain;
